### PR TITLE
fix: declare class types

### PR DESCRIPTION
**Pull request by Kikobeats**
Hello, 

Since this package is not modifying the global scope, the types should be exposed accordingly.

### CODE REVIEW

**Comment by SanderElias** [comment]
@Kikobeats I have a question:
This package _is_ actually adding the `URLPattern` to window (the global scope) when it's missing. 
That means that in code you can do:
```ts
  let pattern = new URLPattern({baseURL, pathname: '/product/*?'});
```
Won't this be untyped with this change?

**Comment by Kikobeats** [comment]
ugh, that's ugly. I recommend to don't do that. Users can do if they need that out of the box

```js
global.URLPattern = require('urlpattern-polyfill')
```

So the library responsibility it's just to ship the pattern logic, nothing more.

**Comment by Schniz** [comment]
I wouldn’t say it’s ugly but it would be extremely beneficial to have a ponyfill next to the polyfill, as the former can allow building the latter but not vice versa

**Comment by Schniz** [comment]
So my suggestion would be `import 'urlpattern-polyfill'` to polyfill and `import URLPattern from 'urlpattern-polyfill/pony'` or any better name other than pony

**Comment by SanderElias** [comment]
@Kikobeats It is a polyfill, not really a library. I get what you are saying tho.
And a large part of me agrees, but we need this to be a drop-in replacement for future browser releases. 

@Schniz Do you have an example of that? We have to work with TS, and there are still some challenges there. Once TS4.7 hits release, I plan to do some refactoring to clean out some other edge-cases, and I might as well set it up like that.

**Comment by SanderElias** [comment]
@Kikobeats I'm going to close this PR. We understand your concern, but at this moment, we can't prevent the need for the global type. 
I'll hope I can address this issue a little bit different by using a ponyfill (once I figure this out ;) )

**Pull request closed without merging**
