### PR TITLE
Escape base URL strings. (Fixes #108)

### LINKED ISSUE #108: Escape pattern characters in base URLs
See:

 * https://github.com/WICG/urlpattern/issues/170
 * https://github.com/WICG/urlpattern/pull/172
 * https://chromium-review.googlesource.com/c/chromium/src/+/4020802

### PR DESCRIPTION
**Pull request by wanderview**

### CODE REVIEW

**Comment by wanderview** [comment]
@kenchris PTAL.  Note, the WPT tests were already updated.  They now pass.  Thanks.

**Comment by wanderview** [comment]
Sorry, I think there might be a problem with this PR.  Hold off on reviewing for now.

**Comment by wanderview** [comment]
Sorry, no its good.  Sorry for my confusion.

**Comment by kenchris** [comment]
Oh nice, thanks for the PR, I was going to look at implementing it myself but you beat me to it!

**Review by kenchris — APPROVED** [review]
This looks great! Approved

**Pull request merged**
