### PR TITLE
Support constructor strings with ipv6 addresses. (#37)

### PR DESCRIPTION
**Pull request by wanderview**

### CODE REVIEW

**Comment by wanderview** [comment]
@kenchris PTAL.  Thanks.

**Comment by wanderview** [comment]
Actually, I need to make some additional changes here.  I forgot there was a second change.

**Comment by wanderview** [comment]
Ok.  This should be ready for review now.  It includes the changes for both wicg/urlpattern#113 and wicg/urlpattern#115.  PTAL.  Thanks.

**Review by kenchris — APPROVED** [review]
This looks good 👍

**Pull request merged**
