### PR TITLE
Fix '.' collapsing issues in pathname patterns. (#60)

### PR DESCRIPTION
**Pull request by wanderview**

### CODE REVIEW

**Comment by wanderview** [comment]
@kenchris PTAL.  Thanks.

**Review by kenchris — APPROVED** [review]
OK, looks good

**Comment by kenchris** [comment]
Do you have other pending PRs or can I release tomorrow?

**Comment by wanderview** [comment]
I do not have any more immediately pending PRs.  And the upstream branch I submitted there has not had any comments yet.  I would say go ahead with the release.

**Comment by wanderview** [comment]
Thanks.

**Pull request merged**
